version: '3'
services:
  zipkin:
    image: openzipkin/zipkin 
    ports:
        - "9411:9411"
  pci:
    image: sleuth/pci 
    logging:
      driver: gelf
      options:
        gelf-address: "udp://127.0.0.1:5000"
        tag: "pci"
  non-pci:
    image: sleuth/non-pci 
    ports:
        - "8080:8080"
    logging:
      driver: gelf
      options:
        gelf-address: "udp://127.0.0.1:5000"
        tag: "non-pci"
